/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    "fc",
    "fc-media-screen",
    "fc-direction-ltr",
    "fc-theme-standard",
    "fc-header-toolbar",
    "fc-toolbar-chunk",
    "fc-next-button",
    "fc-view-harness",
    "fc-daygrid-day-frame",
    "fc-scrollgrid",
    "fc-dayGridMonth-view",
  ],
  theme: {
    extend: {
      colors: {
        headerBlue: "#374370",
        tabs: "#8E95AF",
        white: "#ffffff",
        priority: {
          high: "#5feef8",
          medium: "#c4a8ff",
          low: "#ffd277",
        },
        font: {
          primary: "#ffffff",
          tabInactive: "#8e95af",
          taskDescription: "#4f4f4f",
          placeholder: "#959090",
          filter: "#8E95AF",
          gray: "#4F4F4F",
        },
        background: {
          startContents: "#222841",
          endContents: "#001b41",
          searchBar: "#373f60",
          status: "#2e3551",
          countBox: "#434b70",
          input: "#6a6c93",
          agendaBox: "#2e3551",
          tabs: "#2e3653",
          lightGray: "#DBDBDB",
          extraLightGray: "#f0ebeb",
        },
        border: {
          search: "#817a7a",
          editorTitle: "#001b41",
          editor: "#8f8e8e",
          gray: "#2d2d2d",
          lightGray: "#ccc",
          activeTab: "#5E7FEC",
        },
        button: {
          filter: "#2e3653",
          prevNext: "#f7edff4d",
          add: "#5E7FEC",
          create: "#4A1D94",
          save: "#0851EE",
        },
        hover: {
          add: "#6d8cf3",
          filter: "#343e60",
          dropdown: "#e5e4ee",
          save: "#175ffb",
        },
        scrollbar: {
          track: "#fff6",
          thumb: "#00000026",
        },
        shadow: "#545454",
        backdrop: "#00000080",
        profiles: {
          green: "#92B96F",
          orange: "#FFA42D",
          pink: "#FFA9B0",
          gray: "#9D9D9D",
        },
      },
    },
  },
  plugins: [],
};
